const scanBtn = document.getElementById('scanBtn');
const scanInput = document.getElementById('scanInput');
const scanResult = document.getElementById('scanResult');

function setEx(value) {
  scanInput.value = value;
  scanInput.focus();
}

function formatSignal(signal, type) {
  const cls = type === 'danger' ? 'sig-d' : type === 'warning' ? 'sig-w' : 'sig-s';
  return `<span class="sig ${cls}">${signal}</span>`;
}

function buildFallbackNotice(data) {
  if (data.source !== 'fallback') {
    return '';
  }

  if (data.fallback_reason === 'openai_quota_exceeded') {
    return `
      <div class="result-notice">
        <strong>Fallback mode active</strong>
        <span>OpenAI is currently unavailable for this project because API quota has been exceeded. This result was generated by the local threat detector.</span>
      </div>
    `;
  }

  return `
    <div class="result-notice">
      <strong>Fallback mode active</strong>
      <span>This result was generated by the local threat detector instead of the OpenAI analysis path.</span>
    </div>
  `;
}

function renderResult(data) {
  if (data.error) {
    scanResult.innerHTML = `<div class="result-card"><div class="result-header"><span class="v-label">Error</span></div><div class="result-body"><p class="rs-text">${data.error}</p></div></div>`;
    return;
  }

  const statusClass = data.verdict === 'SAFE' ? 'v-safe' : data.verdict === 'DANGEROUS' ? 'v-danger' : 'v-warn';
  const sourceLabel = data.source === 'fallback' ? 'Fallback analysis' : data.source === 'openai' ? 'OpenAI powered analysis' : 'Threat analysis';
  const signalsHtml = data.signals?.map((signal, index) => formatSignal(signal, data.signal_types?.[index] || 'warning')).join('') || '';
  const fallbackNotice = buildFallbackNotice(data);

  scanResult.innerHTML = `
    <div class="result-card">
      <div class="result-header">
        <div class="v-icon ${statusClass}">${data.verdict[0]}</div>
        <div>
          <div class="v-label">${data.verdict}</div>
          <div class="v-sub">${sourceLabel} · Confidence ${data.confidence}%</div>
        </div>
      </div>
      <div class="result-body">
        ${fallbackNotice}
        <div class="rs">
          <div class="rs-label">Summary</div>
          <div class="rs-text">${data.plain_summary}</div>
        </div>
        <div class="rs">
          <div class="rs-label">Details</div>
          <div class="rs-text">${data.detail}</div>
        </div>
        <div class="rs">
          <div class="rs-label">Signals</div>
          <div class="signals">${signalsHtml}</div>
        </div>
        <div class="rs">
          <div class="rs-label">Action</div>
          <div class="rs-text">${data.action}</div>
        </div>
      </div>
    </div>
  `;
}

async function doScan() {
  const input = scanInput.value.trim();

  if (!input) {
    scanResult.innerHTML = `<div class="result-card"><div class="result-body"><p class="rs-text">Please enter a URL or suspicious message to scan.</p></div></div>`;
    return;
  }

  scanBtn.disabled = true;
  scanBtn.textContent = 'Scanning...';
  scanResult.innerHTML = `<div class="loading"><span class="ld"></span><span class="ld"></span><span class="ld"></span></div>`;

  try {
    const response = await fetch('/api/scan', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ input })
    });

    const data = await response.json();
    renderResult(data);
  } catch (error) {
    scanResult.innerHTML = `<div class="result-card"><div class="result-body"><p class="rs-text">Request failed: ${error.message}</p></div></div>`;
  } finally {
    scanBtn.disabled = false;
    scanBtn.textContent = 'Scan for threats →';
  }
}
